### PR TITLE
Fix config refactor bug

### LINKED ISSUE #645: mmcv version
Traceback (most recent call last):
  File "tools/test.py", line 196, in <module>
    main()
  File "tools/test.py", line 134, in main
    if cfg.test_cfg is None:
  File "/home/cb/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 363, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/cb/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 43, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'

when i test model, above error happened, i try to uninstall mmcv and reinstall mmcv=1.1.6.  
but error also happend

### PR DESCRIPTION
**Pull request by congee524**
fix #645

### CODE REVIEW

**Comment by innerlee** [comment]
Do a global search to make sure that `cfg.test_cfg` does not occur anymore

**Comment by congee524** [comment]
> Do a global search to make sure that `cfg.test_cfg` does not occur anymore

emm, I did a global search but didn't notice it. and only did the training model test.

There should be no problem now

**Comment by innerlee** [comment]
How about `cfg.train_cfg`?

**Comment by congee524** [comment]
> How about `cfg.train_cfg`?

have confirmed it.

**Review by innerlee — APPROVED** [review]

**Review by dreamerlin — APPROVED** [review]

**Pull request merged**
