### PR TITLE
feat(mlu): Support MLU Backend

### PR DESCRIPTION
**Pull request by zgplvyou**
Support Cambricon MLU device for MMaction2.

## Motivation

Support Cambricon MLU device for MMaction2.

## Modification

mmaction/apis/train.py : train on the default device.
tools/test.py : test on the default device.
mmaction/utils/distribution_env.py : choose the default device; build ddp and dp model.

## BC-breaking (Optional)

No BC-breaking

## Use cases (Optional)

you can use the native script  of gpu devices to train the model on mlu devices without any change.

### CODE REVIEW

**Comment by kennymckormick** [comment]
@zgplvyou , please help fix the lint problem

**Review by kennymckormick — APPROVED** [review]

**Comment by zgplvyou** [comment]
train on mlu：
{02e87d3e-5a0d-4f8e-b876-228757deb36d}

**Comment by zgplvyou** [comment]
pytest tests/
{1112c58e-9b7b-4217-a220-b3104451309c}
we got the result of 1 failed, 213 passed, 5 skipped, 333 warnings. and on the master branch, we got the same result. The error comes from mmcv.

**Comment by zgplvyou** [comment]
code coverage:
{f008a0fd-3370-40ea-aa4c-6b0bd1f58a41}
we got the same percent(85%) code coverage as master. And we need run the tests on mlu device to cover the file of "mmaction/utils/distribution_env.py".

**Comment by HarryZJ** [comment]
> pytest tests/ {1112c58e-9b7b-4217-a220-b3104451309c} we got the result of 1 failed, 213 passed, 5 skipped, 333 warnings. and on the master branch, we got the same result.

@kennymckormick it seems like the test_rawframe_decode requires libturbojpeg library, but we didn't installed it in our system.  That's how i guess.

**Comment by kennymckormick** [comment]
> 

LGTM, is it OK to merge this PR now?

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @zgplvyou ！First of all, we want to express our gratitude for your significant PR in the mmaction2 project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
