### PR TITLE
This fix the calculation of the num_frame at L79.

### PR DESCRIPTION
**Pull request by HenglinShi**
## Motivation

This fix the calculation of the num_frame at L79.
Currently, the num of frames (num_frame) is calculated by num_frame * fps. This calculation could be supposed to use the video length in seconds and fps. But the defined label files already provide the number of frames.

### CODE REVIEW

**Comment by hukkai** [comment]
@HenglinShi Hi, thanks for your PR. Are you planning to support a new dataset with the fix? If so, we recommend submit a separate PRs for the dataset to make each PR clear.

**Comment by HenglinShi** [comment]
Hi @hukkai, thanks for your time. I am so sorry that it seems I accidentally submitted two commits in this PR, but one is unwanted. I was only intending to make the PR for [mmaction/localization/ssn_utils.py](https://github.com/open-mmlab/mmaction2/pull/2135/commits/d07d62666ad398c86a5d1d22541392d746e400fd#diff-c5803eeb4dca8a3f30c919e5f1a28ebdc5605ffb65a6dd147c95fde542d4464f). Can we now close this PR? I will submit a clean one with the commit only on that file.

**Comment by hukkai** [comment]
@HenglinShi Yes, you can fix this PR or open a new one.

**Comment by OpenMMLab-Assistant001** [comment]
Hi @HenglinShi ！We are grateful for your efforts in helping improve this open-source project during your personal time. 

Welcome to join OpenMMLab Special Interest Group (SIG) private channel on **Discord**, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "**mmsig + Github ID**" as a remark when adding friends：）

Thank you again for your contribution❤

**Pull request closed without merging**
