### PR TITLE
Fix bug in work_dir.

### PR DESCRIPTION
**Pull request by SuX97**
The `args.work_dir` will never be None, it will only be `''` an empty str. When training without specific work_dir, it results in lots of logs and ckpts saved in $MMACTION2_HOME.

### CODE REVIEW

**Comment by innerlee** [comment]
image

**Comment by SuX97** [comment]
But in `slurm_train.sh`, it will be 
image. @innerlee

**Comment by innerlee** [comment]
that is a bug of slurm_train.sh

**Comment by innerlee** [comment]
2

**Comment by SuX97** [comment]
I vote for change the slurm scripts, just remove the work_dir to PY_ARGS as the user wishes. @dreamerlin

**Comment by dreamerlin** [comment]
Well, we can try plan 2 to see what will happen.

**Comment by innerlee** [comment]
Another choice: abandon `slurm_train.sh` and adopt `slurm_train`

**Pull request merged**
