### PR TITLE
[Fix] build_audio_features

### PR DESCRIPTION
**Pull request by rlleshi**
hotfix glob search

### CODE REVIEW

**Comment by rlleshi** [comment]
Could someone merge this? It's just a single line.

**Comment by ly015** [comment]
Thanks for your help! I made a tiny change to add back the '.' before the extension.

**Review by ly015 — APPROVED** [review]

**Comment by rlleshi** [comment]
That was the original problem :sweat_smile: 

Otherwise, the default arg should be changed from `default='.m4a'` to just `m4a`

**Comment by ly015** [comment]
I think the default arg is `m4a`: https://github.com/open-mmlab/mmaction2/blob/f189c04f4392c9acb79c596e6567a2ed296bc041/tools/data/build_audio_features.py#L293

**Comment by Dai-Wenxun** [comment]
Fixed in #2570

**Pull request closed without merging**
