### PR TITLE
[Fix] Fix hvu object numclasses

### PR DESCRIPTION
**Pull request by kennymckormick**

### CODE REVIEW

**Comment by innerlee** [comment]
any checkpoints need to be updated?

**Comment by kennymckormick** [comment]
> any checkpoints need to be updated?

The ckpt of object baseline needs to be updated, will be uploaded by @dreamerlin . The change is just removing a class from weights of fc, no performance change.

**Comment by innerlee** [comment]
Okay, waiting for the updated checkpoints

**Comment by kennymckormick** [comment]
> Okay, waiting for the updated checkpoints

The checkpoint link has been already updated.

**Review by innerlee — APPROVED** [review]

**Pull request merged**
