### PR TITLE
[Fix] fix flow norm cfg typo

### LINKED ISSUE #692: Wrong Value for flow normalization
`img_norm_cfg` should be `dict(mean=[128, 128], std=[128,128])`, not imagenet one.

### PR DESCRIPTION
**Pull request by congee524**
fix #692

### CODE REVIEW

**Comment by innerlee** [comment]
How to ensure that configs are valid?

**Comment by congee524** [comment]
> How to ensure that configs are valid?

The modified?
Keep them consistent with the norm config in the log file of the `recognition/tsn/README.md`

**Comment by congee524** [comment]
we convert flow_x flow_y to Single channel grayscale image and thus use `mean=[128, 128], std=[128, 128]`

**Comment by innerlee** [comment]
> The modified?

No, the original incorrect one

**Comment by congee524** [comment]
There was a typo when adding. Maybe the reviewer didn't notice it. After all, the training process has no problem.

**Comment by congee524** [comment]
Can't find that PR. It's too long

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
Note to future:
We want our config to be able to reproduce the results. Such typos should be avoided as possible.

**Pull request merged**
