### PR TITLE
[Feature] add c2d_r50 model

### PR DESCRIPTION
**Pull request by InvincibleWyq**
## Modification

add c2d_r50 support (configs, backbone, model)

### CODE REVIEW

**Comment by hukkai** [comment]
@InvincibleWyq Could you train the model and provide logs & checkpoints? Since this model is kind of out-of-date and similar to TSN, we may not have the resources to train the model in the next two months. Without the checkpoints, the models cannot be added.

**Comment by InvincibleWyq** [comment]
@hukkai Hi, I will provide checkpoints & logs & JSON of these two configs on **31, August** (2 days later).  
I've already got **a good precision** of these two models, which perfectly match the original video-nonlocal repo. 
The configs I used are slightly different from the final version, so I'm now training the final version using the exact configs I've committed.

**Comment by InvincibleWyq** [comment]
@hukkai It's true that the nopool version of C2D is similar to TSN. The only difference is that TSN samples 1x1x8 frames, while C2D samples 8x8x1 frames. So if you guys consider it redundant, you can discard C2D_nopool, and only keep standard C2D.

**Comment by InvincibleWyq** [comment]
@hukkai @Dai-Wenxun checkpoint & log & json of c2d & c2d_nopool can be found from computing cluster S1, /mnt/lustre/share_data/wangyiqin/c2d/   and    /mnt/lustre/share_data/wangyiqin/c2d_nopool/
Test result is also listed in both folders.

**Comment by hukkai** [comment]
@InvincibleWyq Could you merge into dev branch?

**Comment by InvincibleWyq** [comment]
@hukkai 
I only forked the master branch, so I re-fork the repo in order to get a dev branch, which automatically closed this PR.

I read the configs of dev branch, but the whole configuration is not familiar to me. Configs and models configuration changes in dev branch, but I won't have the resource to train c2d again under dev branch.

**Pull request closed without merging**
