### PR TITLE
rebenchmark for Pyslowfast comparison

### PR DESCRIPTION
**Pull request by SuX97**
Rebenchmarked on 32G v100 servers.

### CODE REVIEW

**Comment by innerlee** [comment]
Could you explain the `re-`? What is the difference in terms of benchmark setting?

**Comment by SuX97** [comment]
> Could you explain the `re-`? What is the difference in terms of benchmark setting?

My part in benchmark.md(slowfast, slowonly, r2+1d, i3d) is conducted on 16G v100 rather than 32G v100, for fair comparison it is redone now.

**Comment by innerlee** [comment]
could you rebase on master?

**Comment by innerlee** [comment]
benchmark in README might need to be updated also

**Comment by innerlee** [comment]
kindly ping

**Pull request merged**
