### PR TITLE
Reorganize Unittest structure

### PR DESCRIPTION
**Pull request by dreamerlin**
* Migrate unittest files related with data parts into `tests/test_data/` directory.
* Migrate unittest files related with model parts into `tests/test_models/` directory.
* Leave others in `tests/` directory.

### CODE REVIEW

**Comment by innerlee** [comment]
why?

**Comment by dreamerlin** [comment]
> why?

Just to make the file structure clearer. I think it is good to do it since we already have 20+ unittest files.

**Comment by innerlee** [comment]
20 is not a big number

**Comment by dreamerlin** [comment]
Don’t you think these files are messy? : )

**Pull request merged**
