### PR TITLE
Remove redundant code

### PR DESCRIPTION
**Pull request by kennymckormick**

### CODE REVIEW

**Comment by innerlee** [comment]
Since you are at it, I guess the `merge_configs` has been implemented in mmcv?

**Comment by kennymckormick** [comment]
@tangh Hi, tang, seems the code is added by you in PR #198 . It is used in any circumstances during testing?

**Comment by kennymckormick** [comment]
> Since you are at it, I guess the `merge_configs` has been implemented in mmcv?

Yes, we can replace it.

**Comment by tangh** [comment]
> @tangh Hi, tang, seems the code is added by you in PR #198 . It is used in any circumstances during testing?

Hi, these codes are added to avoid an error when someone running test script but have never run the training script. https://github.com/open-mmlab/mmaction2/pull/198#discussion_r492817246

**Comment by kennymckormick** [comment]
> > @tangh Hi, tang, seems the code is added by you in PR #198 . It is used in any circumstances during testing?
> 
> Hi, these codes are added to avoid an error when someone running test script but have never run the training script. [#198 (comment)](https://github.com/open-mmlab/mmaction2/pull/198#discussion_r492817246)

Got it. I think it would be good to check if the output path exists (if not, mkdir), rather than mkdir work_dir

**Review by dreamerlin — APPROVED** [review]

**Pull request merged**
