### PR TITLE
Support efficient video decoder and PIMS decoder

### PR DESCRIPTION
**Pull request by dreamerlin**

### CODE REVIEW

**Comment by dreamerlin** [comment]
unittest and docstring will be updated soon

**Comment by kennymckormick** [comment]
suggest to train one model with PIMS decoder (accurate / efficient) to validate its efficacy.

**Comment by dreamerlin** [comment]
For TSN 1x1x3 UCF-101:
|Setting|Top-1|Top-5|
|:--:|:--:|:--:|
|Decord accurate|82.50|96.93|
|Decord efficient|75.97|92.84|
|PyAV accurate|82.50|96.93|
|PyAV efficient|75.50|93.10|
|PIMS accurate|82.50|96.93|
|PIMS efficient|82.50|96.93|

For TSM 1x1x8 Diving48:
|Setting|Top-1|Top-5|
|:--:|:--:|:--:|
|Decord accurate|77.41|97.06|
|Decord efficient|17.97|53.10|
|PyAV accurate|77.37|97.01|
|PyAV efficient|26.60|63.30|
|PIMS accurate|78.07|97.72|
|PIMS efficient|76.50|97.46|

According to these results, I updated some descriptions in the docstring.

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
Curious aobut the speed of PIMS

**Comment by dreamerlin** [comment]
Speed: Decord > PyAV ≈ PIMS

**Comment by whwu95** [comment]
@dreamerlin  Hi Jintao, it’s better to state that this part of the code comes from [MVFNet](https://github.com/whwu95/MVFNet).

**Comment by jayleicn** [comment]
> Speed: Decord > PyAV ≈ PIMS

Hi @dreamerlin, Do you have a numerical comparison of these video decoders? Like how many times faster can Decord be compared to PyAV? Meanwhile, is Decord used here the cpu version or the gpu version? How's speed comparison between the cpu and gpu verison of Decord? Thanks!

**Pull request merged**
