### PR TITLE
[Improvement] Remove Flips

### PR DESCRIPTION
**Pull request by kennymckormick**

### CODE REVIEW

**Comment by kennymckormick** [comment]
@dreamerlin  Plz take a look.

**Comment by innerlee** [comment]
flop flip

**Comment by innerlee** [comment]
One thing to check is that the modified configs could run successfully, especially for those detection related.
The format bundle in mmdet requires keys like flip directions, so det will raise an error if such keys do not exist.

**Review by dreamerlin — APPROVED** [review]

**Comment by kennymckormick** [comment]
> One thing to check is that the modified configs could run successfully, especially for those detection related.
> The format bundle in mmdet requires keys like flip directions, so det will raise an error if such keys do not exist.

Keys added by Flip ('flip', 'flip_direction') is not further used, besides, we haven't changed the detection config files.

**Pull request merged**
