### PR TITLE
Add colab demo description

### PR DESCRIPTION
**Pull request by dreamerlin**

### CODE REVIEW

**Comment by innerlee** [comment]
?

**Comment by dreamerlin** [comment]
> ?

Add some description in README.md，and update the the colab link to the master one. (Other wise, it will direct to the wrong link for my fork branch, which has been deleted.)

**Comment by innerlee** [comment]
why change the badges

**Comment by dreamerlin** [comment]
> why change the badges

Ops, It should be a build badge. And I think it is still necessary to indicate the docs site since the badge is Easily overlooked.

**Pull request merged**
