### PR TITLE
fix sample_length bug in long_video_demo

### PR DESCRIPTION
**Pull request by fangwudi**
fix sample_length bug in long_video_demo

### CODE REVIEW

**Comment by dreamerlin** [comment]
It is not a bug. Actually, `sample_length` means the length of the sampled frames, which is equal to `clip_len` x `num_clips`

**Comment by innerlee** [comment]
@fangwudi Have met any problems running the script?

**Comment by fangwudi** [comment]
> Thanks your attention.
> 
> It is not a bug. Actually, `sample_length` means the length of the sampled frames, which is equal to `clip_len` x `num_clips`

according to readme in demo, sample_length indicates the size of temporal window from which you sample frames, which equals to clip_len x frame_interval.

**Comment by dreamerlin** [comment]
> > Thanks your attention.
> > It is not a bug. Actually, `sample_length` means the length of the sampled frames, which is equal to `clip_len` x `num_clips`
> 
> according to readme in demo, sample_length indicates the size of temporal window from which you sample frames, which equals to clip_len x frame_interval.

It is about the temporal window which contains the selected frames. Maybe The docs should be modified.

**Comment by fangwudi** [comment]
> > > Thanks your attention.
> > > It is not a bug. Actually, `sample_length` means the length of the sampled frames, which is equal to `clip_len` x `num_clips`
> > 
> > 
> > according to readme in demo, sample_length indicates the size of temporal window from which you sample frames, which equals to clip_len x frame_interval.
> 
> It is about the temporal window which contains the selected frames. Maybe The docs should be modified.

so , temporal window should be modifed as  clip_len x frame_interval x num_clips ?

**Comment by dreamerlin** [comment]
> > > > Thanks your attention.
> > > > It is not a bug. Actually, `sample_length` means the length of the sampled frames, which is equal to `clip_len` x `num_clips`
> > > 
> > > 
> > > according to readme in demo, sample_length indicates the size of temporal window from which you sample frames, which equals to clip_len x frame_interval.
> > 
> > 
> > It is about the temporal window which contains the selected frames. Maybe The docs should be modified.
> 
> so , temporal window should be modifed as clip_len x frame_interval x num_clips ?

I mean the length of this 'temporal window' should be equal to `clip_len` x `num_clips`

**Comment by innerlee** [comment]
@fangwudi @dreamerlin Any conclusion by now?

**Comment by irvingzhang0512** [comment]
I think sampling strategy is not Inconsistent between demo(webcam demo and long video demo) and training/testing(train.py test.py).

During training/testing, we sample certain frames(`sample_length`) from temporal window. For example, `8x8x1` samples 8 frames from 64 frames.

In webcam demo and long video demo, we sample frames in consecutive frames. For example, `8x8x1` samples 8 frames from 8 frames. In other words, temporal window length equals to sample length.

**Comment by fangwudi** [comment]
you're right. in this long video demo.py , I need to use "input-step" insted of "frame_interal" in config. maybe the code can directly use "frame_interal" in config. I'll close this merge-request.

**Comment by OpenMMLab-Coodinator** [comment]
Hi @fangwudi  ！We are grateful for your efforts in helping improve this open-source project during your personal time.
Welcome to join OpenMMLab Special Interest Group (SIG) , where you can share your experiences, ideas, and build connections with like-minded peers.

To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
