### PR TITLE
Fix precise_bn unittest.

### PR DESCRIPTION
**Pull request by SuX97**

### CODE REVIEW

**Comment by congee524** [comment]
the bug will be fixed in #433

**Comment by kennymckormick** [comment]
(Not related to this PR) BTW, have you changed the priority of the precise_bn_hook? I think maybe changing it to the right priority may lead to performance improvement @SuX97

**Comment by SuX97** [comment]
@kennymckormick , haven't tested yet. I think the difference will not be significant. Before changing, only the bn updating of the last epoch will be ignored, since the updating in epoch x will be saved by save_checkpoint of epoch x+1. I'll change it after the verification.

**Comment by SuX97** [comment]
Duplicated PR.

**Pull request closed without merging**
