### PR TITLE
Fix thumos14 preparing

### PR DESCRIPTION
**Pull request by ShoufaChen**
* unzip TH14_validation_set_mp4.zip with `-j`
* fix folder name in `extract_rgb_frames.sh`

### CODE REVIEW

**Comment by innerlee** [comment]
@tony2016uestc Could you review this change?

**Comment by tony2016uestc** [comment]
OK.

**Comment by tony2016uestc** [comment]
Since I do not have the right to modify PR, I have to open another PR(to set all 'val' to 'validation').

**Comment by dreamerlin** [comment]
I vote for `val` rather than validation.

**Comment by innerlee** [comment]
@tony2016uestc actually, i think `val` is more commonly used

**Review by dreamerlin — APPROVED** [review]

**Comment by innerlee** [comment]
You may check the `-j` option. I'm not sure its effect

**Comment by ShoufaChen** [comment]
without `-j`, after unzip:
```
videos/test/H14_test_set_mp4/video_test_0000001.mp4
...
```

with `-j`:
```
videos/test/video_test_0000001.mp4
...
```

**Comment by dreamerlin** [comment]
Help to modify some details in other '.sh'. @tony2016uestc cc.

**Comment by innerlee** [comment]
@ShoufaChen Thanks, that's exactly what I was trying to understand.

**Review by innerlee — APPROVED** [review]

**Comment by tony2016uestc** [comment]
All modifications have been checked. 
This PR can be merged. @innerlee

**Pull request merged**
