### PR TITLE
[Feature] Support topk customizing in models/heads/base.py

### PR DESCRIPTION
**Pull request by jamiechoi1995**
Support topk customizing in models/heads/base.py

### CODE REVIEW

**Review by kennymckormick — APPROVED** [review]

**Comment by kennymckormick** [comment]
To merge this PR, please help to fix the lint problem.

**Comment by jamiechoi1995** [comment]
```
yapf.....................................................................Failed
- hook id: yapf
- files were modified by this hook
```
I have no idea why yapf failed, can you please help me take a look of it? @kennymckormick

**Comment by dreamerlin** [comment]
> ```
> yapf.....................................................................Failed
> - hook id: yapf
> - files were modified by this hook
> ```
> 
> I have no idea why yapf failed, can you please help me take a look of it? @kennymckormick

I try to modify your PR but failed, since Github "removed the Support for password authentication on August 13, 2021. Please use a personal access token instead."

You can refer to https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md to install pre-commit and run `pre-commit run --all-files` to fix it. 

Or if you want, I can renew a PR for it

**Comment by kennymckormick** [comment]
Just as @dreamerlin said, you need to run `pre-commit run --all-files` locally. You can try it next time, I have fixed the lint problem of this PR.

**Comment by jamiechoi1995** [comment]
Thank you @kennymckormick @dreamerlin , I try to install pre-commit but failed due to the rbenv installation. I will run pre-commit before my next commit. Thank you for your help 👍

**Pull request merged**
