### PR TITLE
Add faq for how to fix stages of backbone when finetuning a model

### PR DESCRIPTION
**Pull request by dreamerlin**

### CODE REVIEW

**Comment by innerlee** [comment]
The instruction tell users to modify codes by themselves. It is okay by itself.

Is it possible to support freezing stages for commonly used backbones?

**Comment by dreamerlin** [comment]
> The instruction tell users to modify codes by themselves. It is okay by itself.
> 
> Is it possible to support freezing stages for commonly used backbones?

For current support model backbones except `C3D`, users can set `frozen_stages` to freeze stages. Actually, all backbone inherit from `ResNet` or `ResNet3D` support freeze stages

**Comment by dreamerlin** [comment]
> > The instruction tell users to modify codes by themselves. It is okay by itself.
> > Is it possible to support freezing stages for commonly used backbones?
> 
> For current supported model backbones except `C3D`, users can set `frozen_stages` to freeze stages. Actually, all backbone inherit from `ResNet` or `ResNet3D` support freeze stages

MobileNetV2 also supports it

**Comment by innerlee** [comment]
Cool then this faq could list the supported backbones as bonus info

**Review by innerlee — APPROVED** [review]

**Pull request merged**
