### PR TITLE
Remove train test cfg in bmn and bsn

### LINKED ISSUE #662: Localizer train cfg & test cfg ?

### PR DESCRIPTION
**Pull request by congee524**
`train_cfg` and `test_cfg` are useless in bmn and bsn.

fix #662

### CODE REVIEW

**Comment by congee524** [comment]
Ignore mdb file in tests/data which is produced by `lfb` and it changes each time we run `pytest`.

**Comment by innerlee** [comment]
Pls remove the unrelated changes on mdb files

**Comment by congee524** [comment]
Since we remove train_cfg and test_cfg in bmn and bsn, we have to modify tools/test.py to avoid introducing test_cfg

**Comment by congee524** [comment]
@SuX97 kindly ping :p

**Review by SuX97 — APPROVED** [review]
LGTM as long as it works.

**Comment by skyqwe123** [comment]
@congee524 Please give me some advice, Thanks

What does the feature's CSV file refer to? Is there an example for reference?

`@PIPELINES.register_module()
class LoadLocalizationFeature:
    """Load Video features for localizer with given video_name list.
    **Required keys are "video_name" and "data_prefix", added or modified keys
    are "raw_feature".**
    Args:
        raw_feature_ext (str): Raw feature file extension.  Default: '.csv'.
    """

    def __init__(self, raw_feature_ext='.csv'):
        valid_raw_feature_ext = ('.csv', )
        if raw_feature_ext not in valid_raw_feature_ext:
            raise NotImplementedError
        self.raw_feature_ext = raw_feature_ext

    def __call__(self, results):
        """Perform the LoadLocalizationFeature loading.
        Args:
            results (dict): The resulting dict to be modified and passed
                to the next transform in pipeline.
        """
        video_name = results['video_name']
        data_prefix = results['data_prefix']
        data_path = osp.join(data_prefix, video_name + self.raw_feature_ext)
        **raw_feature = np.loadtxt(
            data_path, dtype=np.float32, delimiter=',', skiprows=1)**

        results['raw_feature'] = np.transpose(raw_feature, (1, 0))
        return results`

**Pull request merged**
