### PR TITLE
[Feature] Support Pytorchvideo Transforms

### PR DESCRIPTION
**Pull request by irvingzhang0512**
## Motivation

[PytorchVideo](https://github.com/facebookresearch/pytorchvideo) support a lot of transforms for videos(My chinese notes [here](https://blog.csdn.net/irving512/article/details/118637392)). Most of the transforms are already supported in MMAction2.

For me, `RandAugment` and `Augmix` seem to be useful in MMAction2.

## Modification

+ [x] Add PytorchVideo augmentation pipeline, support AugMix/RandAugment and 4 resize & crop transforms.
+ [x] unittest
+ [x] Demo config
+ [x] changelog
+ [x] pytorch >= 1.8.0 and torchvision >= 0.9.0 is required.
+ [x] Visualize results for `RandAugment`, `AugMix` and `RandomResizedCrop` with shift mode
+ [x] checkpoints and related docs.

## Use cases (Optional)

Two sample PytorchVideo transform pipelines are listed as follows: 
+ `dict(type='pytorchvideo.AugMix')` 
+ `dict(type='pytorchvideo.RandomResizedCrop', target_height=224, target_width=224, scale=(0.8, 1.0), aspect_ratio=(0.75, 1.33), shift=True)`

Add a demo config `configs/recognition/tsm/tsm_r50_augmix_1x1x8_50e_sthv1_rgb.py`. Add AugMix transforms in pipeline

```python
train_pipeline = [
    dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=8),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='MultiScaleCrop',
        input_size=224,
        scales=(1, 0.875, 0.75, 0.66),
        random_crop=False,
        max_wh_scale_gap=1,
        num_fixed_crops=13),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='pytorchvideo.AugMix'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
```

## Drawback

Following #972, this pipeline transforms imgs from `list[ndarray(h, w, 3)]` -> `torch.tensor` in shape `t, c, h, w` -> `list[ndarray(h, w, 3)`, which may be quite slow

## training results

Train tsm-r50 on sthv1 with pytorchvideo.RandAugment & pytorchvideo.AugMix
image

## Visualization Sample

Raw sample from sthv1
sthv1-raw

Augmix
sthv1-augmix

RandAugment
sthv1-randaugment

RandomResizedCrop with shift mode
sthv1-randomresizedcrop

### CODE REVIEW

**Comment by kennymckormick** [comment]
Great, do these transformations help improve the recognition performance under your experiment settings?

**Comment by irvingzhang0512** [comment]
> Great, do these transformations help improve the recognition performance under your experiment settings?

For my own datasets, it helps a little. Will train sthv1 with RandAugment/AugMix as an example.

**Comment by dreamerlin** [comment]
@kennymckormick Plz help for CI about installing pytorchvideo

**Comment by irvingzhang0512** [comment]
@kennymckormick Please help to upload checkpoints/logs/jsons 
https://wp.cethik.com:443/link/9AD3E0ED199AD05F69C1E638BFF2A2C7

**Comment by dreamerlin** [comment]
Since you are here, plz use `pre-commit run --all-files` to correct the lint failure

**Comment by irvingzhang0512** [comment]
> Since you are here, plz use `pre-commit run --all-files` to correct the lint failure

done

**Review by dreamerlin — APPROVED** [review]

**Pull request merged**
