### PR TITLE
[Docs] Update supported dataset of docs_zh-CN

### PR DESCRIPTION
**Pull request by congee524**
Preview the docs_zh-CN at https://congee524-mmaction2.readthedocs.io/zh_CN/latest

### CODE REVIEW

**Review by dreamerlin — APPROVED** [review]

**Review by dreamerlin — CHANGES_REQUESTED** [review]
Please help to correct the name of Kinetics and others like `HVU` etc from `README_zh_CN.md` to `README_zh-CN.md`

**Review by innerlee — APPROVED** [review]

**Comment by congee524** [comment]
> Please help to correct the name of Kinetics and others like `HVU` etc from `README_zh_CN.md` to `README_zh-CN.md`

I think I have already renamed them.

**Comment by innerlee** [comment]
image

Some are missed

**Comment by congee524** [comment]
> image
> 
> Some are missed

Which folder is this? I can't find it

**Comment by congee524** [comment]
image

**Comment by innerlee** [comment]
Cool

**Pull request merged**
