### PR TITLE
[Improvement] save best ckpt during training

### LINKED ISSUE #460: Training not storing best model
Hello,

I am trying to use mmaction2 to train on my custom dataset. I am able to train i3d, slowfast, slowonly and TSN. 

Due to limitation in hard drive space I am not storing all the epochs. For example I created a check point file for every 3 epochs and the best model is at epoch 2. The epoch 2 checkpoint is not created. Is there anything I can do to store the best eopoch checkpoints even tho I write checkpoints for every 3 epochs, `checkpoint_config = dict(interval=3)`?

Please let me know if this is possible.

### PR DESCRIPTION
**Pull request by irvingzhang0512**
Fix #460 

Add arg `save_best_ckpt` for eval hook,. If set to True, then save best ckpt in `work_dir` with name `best_{best_socre}_{epoch_id}.pth`

+ [x] modify eval hook
+ [x] add unittest
+ [x] add changelog
+ [ ] fix codecov

### CODE REVIEW

**Comment by dreamerlin** [comment]
Thanks for your contribution
Lately, we will refactor the `EvalHook` in the PR https://github.com/open-mmlab/mmaction2/pull/395, which may then be applied into MMCV for other OpenMMLab repo usage:

1.  Add `by_epoch` param to determine perform evaluation by epoch or by iteration.
2.  Add automatically assign a compare key when users do not set one.
3.  Save checkpoint by creating a symlink as well as record best info in runner hook meta
4.  Refactor the code structure 

you can modify based on https://github.com/open-mmlab/mmaction2/pull/395

**Comment by irvingzhang0512** [comment]
> Thanks for your contribution
> Lately, we will refactor the `EvalHook` in the PR #395, which may then be applied into MMCV for other OpenMMLab repo usage:
> 
> 1. Add `by_epoch` param to determine perform evaluation by epoch or by iteration.
> 2. Add automatically assign a compare key when users do not set one.
> 3. Save checkpoint by creating a symlink as well as record best info in runner hook meta
> 4. Refactor the code structure
> 
> you can modify based on #395

Sure, I will close this pr and create a new one tonight.

**Comment by dreamerlin** [comment]
no hurry, you can make a new pr when https://github.com/open-mmlab/mmaction2/pull/395 is merged

**Comment by irvingzhang0512** [comment]
> no hurry, you can make a new pr when #395 is merged

ok

**Pull request closed without merging**
