### PR TITLE
[Fix] Fix wrong variable name in ava_utils.py

### PR DESCRIPTION
**Pull request by jamiechoi1995**
The `action_id` in `read_csv()` should be `label`

### CODE REVIEW

**Comment by kennymckormick** [comment]
Maybe I didn't quite get it. What's the purpose of this PR, I think action_id is just an internal variable (You can call it whatever you want. )

**Comment by jamiechoi1995** [comment]
> Maybe I didn't quite get it. What's the purpose of this PR, I think action_id is just an internal variable (You can call it whatever you want. )

In my opinion, when someone needs to modify the code to fit their own dataset, using the wrong name can cause misunderstanding.

**Comment by kennymckormick** [comment]
As mentioned here, we directly adapt this part from the [official AVA evaluation code](https://github.com/activitynet/ActivityNet/blob/master/Evaluation/get_ava_performance.py). So we prefer not to change them.

**Comment by jamiechoi1995** [comment]
Got it. You can close this PR or leave it open. I am OK with it.

**Pull request closed without merging**
