### PR TITLE
Add colab demo

### PR DESCRIPTION
**Pull request by dreamerlin**

### CODE REVIEW

**Comment by innerlee** [comment]
how to check if it works

**Comment by dreamerlin** [comment]
> how to check if it works
This ipython file is run in colab. you can click the colab link to re-run it.

**Comment by innerlee** [comment]
Lets merge it and fix it if something goes wrong

**Comment by dreamerlin** [comment]
> Lets merge it and fix it if something goes wrong

Okay.

**Comment by innerlee** [comment]
Pls rename the file to lowercase

**Pull request merged**
