### PR TITLE
[Fix] typo of tsm-r50 & sthv2

### PR DESCRIPTION
**Pull request by irvingzhang0512**
## TYPO

In tsm, `num_clips` should be the same for train/val/test pipelines.

## CANNOT reproduce tsm-r50/sthv2 results

I did some tests with tsm-r50/shtv2 these days and **CANNOT** reproduce the results from the model zoo.

Generally speaking
1) ckpt from the model zoo leads to WORSE results than that of model zoo reports. 
2) ckpt trained by myself leas to **BETTER** results than that of model zoo reports.

**Can anyone verify this?**

|model|top1/5 accuracy for efficient mode|top1/5 accuracy for accurate mode|
|:-:|:-:|:-:|
|copy from model zoo|57.86/84.67 |61.12/86.26|
|test with the [model zoo ckpt](https://download.openmmlab.com/mmaction/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb/tsm_r50_1x1x8_50e_sthv2_rgb_20200912-033c4ac6.pth) **by myself**|55.56/82.94|56.92/83.92|
|trained by myself with the [default config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py), trained ckpt [here](https://wp.cethik.com:443/link/9EC6E825165CC8AF556C6DDFC1FBC217)|58.91/85.10|61.68/86.71|

PS: I'm using videos instead of rawframes.
PPS: efficient/accurate test pipelines are listed as follows
```python
# efficient
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]

# accurate
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        twice_sample=True,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
```

### CODE REVIEW

**Comment by congee524** [comment]
I remember that when I trained TAM, I copied this TSM config file as the TAM sthv1&2 config file.
Later, I found `num_ clips` is wrong, but I forgot to fix the typo in TSM.

Many thanks.

**Comment by irvingzhang0512** [comment]
@congee524  Can you help to verify the tsm-r50 sthv2 model ckpt on your sthv2 dataset?
Unlike kinetics, our sthv2 datasets are supposed to be exact the same...

**Comment by congee524** [comment]
> @congee524 Can you help to verify the tsm-r50 sthv2 model ckpt on your sthv2 dataset?
> Unlike kinetics, our sthv2 datasets are supposed to be exact the same...

yeah, I'm working on it.

**Comment by congee524** [comment]
emmm, I only have rawframes dataset now, and there're some problems when testing with rawframes.

**Comment by dreamerlin** [comment]
Not wrong
image

**Comment by dreamerlin** [comment]
Videos are not totally equal to rawframes, since dense-encoding, key-frames or something else in Videos may affect. But we will adopt your ckpt for video result :)

**Comment by irvingzhang0512** [comment]
> Videos are not totally equal to rawframes, since dense-encoding, key-frames or something else in Videos may affect. But we will adopt your ckpt for video result :)

How did you extract frames? denseflow or opencv? I may have a try tomorrow

**Comment by dreamerlin** [comment]
If you just want to extract rgb frames, use ffmpeg is OK. For RGB extraction, Denseflow is equal to FFmpeg. We use Denseflow for it.

**Review by kennymckormick — DISMISSED** [review]

**Review by kennymckormick — COMMENTED** [review]
If it is a feature (Is this twice sampling for TSM?) rather than a typo, maybe we need to add some explanation. @dreamerlin

**Review by kennymckormick — COMMENTED** [review]
If it is a feature (Is this twice sampling for TSM?) rather than a typo, maybe we need to add some explanation. @dreamerlin

**Comment by irvingzhang0512** [comment]
> Seems this PR still needs further discussion...

I'll do more tests about the difference between video dataset and rawframe dataset.

**Comment by dreamerlin** [comment]
> If it is a feature (Is this twice sampling for TSM?) rather than a typo, maybe we need to add some explanation. @dreamerlin

It is a typo in config file. twice sample tips are written [here](https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/tsm)

**Comment by dreamerlin** [comment]
image
45.19 for efficient, 44.67 for accurate

**Comment by irvingzhang0512** [comment]
> image
> 45.19 for efficient, 44.67 for accurate

..Interesting... I will verify the results on rawframe dataset tonight... After that, we may add ckpt trained by sthv2 video to model zoo.

**Comment by irvingzhang0512** [comment]
Still couldn't reproduce the results. ​Extract frames by ffmpeg `ffmpeg -i \"{}\" -q:v 1 \"{}/img_%05d.jpg\"`

@dreamerlin Could you upload the filelist? 
I will double check sthv2 videos and annotations, and extract frames by opencv script.

**Comment by dreamerlin** [comment]
[sth-v2_train_list.txt](https://github.com/open-mmlab/mmaction2/files/6109097/sth-v2_train_list.txt)
[sth-v2_val_list.txt](https://github.com/open-mmlab/mmaction2/files/6109098/sth-v2_val_list.txt)

**Comment by irvingzhang0512** [comment]
I'm a little confused... Our filelist are the same but I couldn't reproduce model zoo results.

Let me make it clear.

+ [ckpt: tsm_r50_1x1x8_50e_sthv2_rgb_20200912-033c4ac6.pth](https://download.openmmlab.com/mmaction/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb/tsm_r50_1x1x8_50e_sthv2_rgb_20200912-033c4ac6.pth)
+ [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py), fix `num_clips=8` instead of 16.
+ testing command: `./tools/dist_test.sh configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py checkpoints/tsm_r50_1x1x8_50e_sthv2_rgb_20200912-033c4ac6.pth 4 --eval top_k_accuracy`

Did I miss something?

TODO:
+ test other something-something-v2 models(i3d, tsm-r101, etc.)
+ extract frames by denseflow next week.
@dreamerlin Or do you have time to test the model zoo ckpt on sthv2 VideoDataset?

**Comment by irvingzhang0512** [comment]
Two issues about extract sthv2 rgb frames by denseflow with `tools/data/sthv2/extract_rgb_frames.sh`

1. It's extremely slow... Runing the script 2-3hours, only processed 8k+ videos. There are 220k videos in sthv2...
2. `start_id` for the extracted frames is `0`, that is to say, `img_00000.jpg` exists...

@dreamerlin @innerlee Any comments about this?

**Comment by innerlee** [comment]
> extremely slow

Is is run on SSD? If disk io is fine, then it can be un in parallel

> img_00000.jpg

yes. There is a config for start index in Dataset

**Comment by irvingzhang0512** [comment]
> Is is run on SSD? If disk io is fine, then it can be un in parallel

Yes, it's run on SSD. I tried to extract frames by opencv yesterday, it's much faster.

> yes. There is a config for start index in Dataset

Of source we can handle this by modifying config files. However, maybe we should add some docs to remind users.. I'll be a little confused if I followed provided tutorials to prepare datasets but couldn't train/test with default configs.

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
@irvingzhang0512 I merged this since the typo fix is correct. Further discussions on reproducing results can be moved to a new issue

**Pull request merged**
