### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by dreamerlin**
* Add arguments explanation for `demo.py`.
* Add example scripts for `demo.py`.
* Add `moviepy` installation steps in `install.md`.

### CODE REVIEW

**Comment by dreamerlin** [comment]
Examples run successfully in this [code](https://github.com/open-mmlab/mmaction2/pull/80).

**Comment by innerlee** [comment]
(oops no, clicked wrong button.)

still suggest that the order be (width, height)

**Comment by dreamerlin** [comment]
> (oops no, clicked wrong button.)
> 
> still suggest that the order be (width, height)

set (w, h) for `--target-resolution` args in demo.py by this [change](https://github.com/open-mmlab/mmaction2/pull/80/commits/f2ef6e05d4e29cfc3085d94fc1a28fd17ac7400a)

**Comment by innerlee** [comment]
cool

**Pull request merged**
