### PR TITLE
[Fix] fix data preparation bug

### PR DESCRIPTION
**Pull request by dreamerlin**

### CODE REVIEW

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
scripts are too easy to be break. hope someone could add scripts to tests

**Comment by yuhuixu1993** [comment]
Thanks for your contribution, I merged the updated tools/sthv2. It seems that the problem of sthv2 still exists.

**Comment by dreamerlin** [comment]
> Thanks for your contribution, I merged the updated tools/sthv2. It seems that the problem of sthv2 still exists. @dreamerlin. Do I need to regenerate the raw frames?

Actually not. Is It the same problem? I test it and go with problems. BTW, it seems necessary to add unittest for the dataset preparation : )

**Comment by yuhuixu1993** [comment]
@dreamerlin ,  I have solved it, thanks for your contribution!

**Comment by dreamerlin** [comment]
> @dreamerlin , I have solved it, thanks for your contribution!

Glad to hear that !

**Pull request merged**
