### PR TITLE
[Improvement] Change ResNet3D default value for stem with BC

### PR DESCRIPTION
**Pull request by dreamerlin**

### CODE REVIEW

**Comment by dreamerlin** [comment]
@kennymckormick need double-checking

**Comment by innerlee** [comment]
Any reason?

**Comment by dreamerlin** [comment]
Our ResNet3D refers to https://github.com/open-mmlab/mmaction/blob/master/mmaction/models/tenons/backbones/resnet_i3d.py, whose stride is 2. And Since we use ResNet3D as a basic module, it is more common to set those as 1 for usage. @kennymckormick What do you think of?

**Review by kennymckormick — APPROVED** [review]

**Comment by kennymckormick** [comment]
> Our ResNet3D refers to https://github.com/open-mmlab/mmaction/blob/master/mmaction/models/tenons/backbones/resnet_i3d.py, whose stride is 2. And Since we use ResNet3D as a basic module, it is more common to set those as 1 for usage. @kennymckormick What do you think of?

I think changing the default value is better.

**Comment by innerlee** [comment]
Old ckpts will suddenly refuse to work, no?

**Comment by dreamerlin** [comment]
> Old ckpts will suddenly refuse to work, no?

It doesn't affect the old ckpts, since current configs in the PRs are the same with the old ones.

**Comment by irvingzhang0512** [comment]
FYI SlowFast I3D's stem maxpooling uses `kernel_size=[1, 3, 3], stride=[1, 2, 2], padding=[0, 1, 1]`.
Related codes are [here](https://github.com/facebookresearch/SlowFast/blob/923e9470b30ac7749af563362eed77339375c82e/slowfast/models/stem_helper.py#L192-L194)

**Pull request merged**
